[package]
name = "mwc-bitcoin"
version = "0.27.2"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/mwcproject/rust-bitcoin"
repository = "https://github.com/mwcproject/rust-bitcoin"
documentation = "https://docs.rs/bitcoin/"
description = "General purpose library for using and interoperating with Bitcoin and other cryptocurrencies."
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"
edition = "2024"

[lib]
name = "mwc_bitcoin"
path = "src/lib.rs"

[features]
base64 = [ "base64-compat" ]
fuzztarget = []
secp-recovery = []
serde = ["dep:serde", "bitcoin_hashes/serde"]
unstable = []
use-serde = ["serde"]

[dependencies]
bech32 = "0.12"
bitcoin_hashes = { version = "1.0", features = ["hex"] }

base64-compat = { version = "1.0", optional = true }
bitcoinconsensus = { version = "0.106", optional = true }
serde = { version = "1", features = [ "derive" ], optional = true }

mwc_secp256k1zkp = { git = "https://github.com/mwcproject/rust-secp256k1-zkp", version = "0.8.0", tag = "0.8.0", features = ["bullet-proof-sizing"] }

[dev-dependencies]
serde_json = "1"
serde_test = "1"
