on: [push, pull_request]

name: Continuous integration

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: stable
            env:
              DO_COV: true
              AS_DEPENDENCY: true
          - rust: beta
            env:
              AS_DEPENDENCY: true
          - rust: nightly
            env:
              DO_FUZZ: true
              DO_BENCH: true
              AS_DEPENDENCY: true
          - rust: 1.29.0
            env:
              AS_DEPENDENCY: true
              PIN_VERSIONS: true
    steps:
      - name: Install test dependencies
        run: sudo apt-get install -y binutils-dev libunwind8-dev libcurl4-openssl-dev libelf-dev libdw-dev cmake gcc libiberty-dev
      - name: Checkout Crate
        uses: actions/checkout@v2
      - name: Checkout Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Running test script
        env: ${{ matrix.env }}
        run: ./contrib/test.sh